# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import grading.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_manager', '0044_auto_20160201_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring_Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', grading.fields.IntegerRangeField(verbose_name='opening argument slide show                                 (5-10)')),
                ('teamArg', grading.fields.IntegerRangeField(verbose_name='team argument (5-10)')),
                ('crossEx', grading.fields.IntegerRangeField(verbose_name='raw cross-examination score                                 (5-10)')),
                ('decorum', models.BooleanField(verbose_name='decorum penalty?')),
                ('rebuttal', grading.fields.IntegerRangeField(verbose_name='raw rebuttal score (5-10)')),
                ('time', models.BooleanField(verbose_name='time violation?')),
                ('newArg', models.BooleanField(verbose_name='new line of argument                                  or substantial new evidence?')),
                ('participation', models.BooleanField(verbose_name='participation penalty?                                         (not everyone spoke)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manager.Student_Group')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manager.Judge')),
            ],
            options={
                'verbose_name': 'Scoring Sheet',
                'verbose_name_plural': 'Scoring Sheets',
            },
        ),
        migrations.CreateModel(
            name='Student_Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTime', models.CharField(max_length=140)),
                ('score', grading.fields.IntegerRangeField(verbose_name='RAW individual score (5-10)')),
                ('time', models.BooleanField(verbose_name='time violation?')),
                ('scoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.Scoring_Sheet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manager.Student')),
            ],
            options={
                'verbose_name': 'Student Argument',
                'verbose_name_plural': 'Student Arguments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='scoring_sheet',
            unique_together=set([('group', 'judge')]),
        ),
    ]
