# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_argument',
            name='student',
            field=models.CharField(max_length=140),
        ),
    ]
