# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 18:53
from __future__ import unicode_literals

from django.db import migrations
import grading.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_auto_20170329_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoring_sheet',
            name='crossEx',
            field=grading.fields.DecimalRangeField(decimal_places=2, max_digits=4, verbose_name='raw cross-examination score                                 (5-10)'),
        ),
        migrations.AlterField(
            model_name='scoring_sheet',
            name='opening',
            field=grading.fields.DecimalRangeField(decimal_places=2, max_digits=4, verbose_name='opening argument slide show                                 (5-10)'),
        ),
        migrations.AlterField(
            model_name='scoring_sheet',
            name='rebuttal',
            field=grading.fields.DecimalRangeField(decimal_places=2, max_digits=4, verbose_name='raw rebuttal score (5-10)'),
        ),
        migrations.AlterField(
            model_name='scoring_sheet',
            name='teamArg',
            field=grading.fields.DecimalRangeField(decimal_places=2, max_digits=4, verbose_name='team argument (5-10)'),
        ),
        migrations.AlterField(
            model_name='student_argument',
            name='score',
            field=grading.fields.DecimalRangeField(decimal_places=2, max_digits=4, verbose_name='RAW individual score (5-10)'),
        ),
    ]
