# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0018_auto_20151210_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='judge_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manager.Judge_Group'),
        ),
    ]
