# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0019_auto_20151210_0501'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debate',
            unique_together=set([('debate_group', 'schedule'), ('judge_group', 'schedule'), ('schedule', 'isPresenting')]),
        ),
    ]
