# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0021_auto_20151213_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='judge_group',
        ),
    ]
