# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0022_remove_debate_judge_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='judge_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group_manager.Judge_Group'),
        ),
    ]
