# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0024_auto_20151213_0454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('period', 'date', 'judge_group'), ('period', 'location', 'date')]),
        ),
    ]
