# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0026_auto_20151213_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate_group',
            name='affTeam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affTeam', to='group_manager.Student_Group', verbose_name='Affirmative Team'),
        ),
        migrations.AlterField(
            model_name='debate_group',
            name='negTeam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negTeam', to='group_manager.Student_Group', verbose_name='Negative Team'),
        ),
    ]
