# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0028_auto_20151214_2233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debate',
            unique_together=set([('debate_group', 'schedule'), ('debate_group', 'isPresenting'), ('schedule', 'isPresenting')]),
        ),
    ]
