# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0032_auto_20151217_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_group',
            name='number',
            field=models.IntegerField(),
        ),
    ]
