# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0035_auto_20151218_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
