# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0037_auto_20160105_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manager.Student_Group'),
        ),
    ]
