# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0038_auto_20160105_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group_manager.Topic'),
        ),
    ]
