# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0039_auto_20160106_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Topic',
            new_name='topic',
        ),
    ]
