# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0040_auto_20160106_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_group',
            options={'ordering': ['teacher__last_name', 'number'], 'verbose_name': 'Student Group', 'verbose_name_plural': 'Student Groups'},
        ),
    ]
