# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0041_auto_20160108_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate_group',
            name='affTeam',
        ),
        migrations.RemoveField(
            model_name='debate_group',
            name='negTeam',
        ),
        migrations.DeleteModel(
            name='Debate_Group',
        ),
    ]
