# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_manager', '0042_auto_20160111_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
