# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_manager', '0044_auto_20160201_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=140, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.AlterModelOptions(
            name='student_group',
            options={'ordering': ['teacher__user__last_name', 'number'], 'verbose_name': 'Student Group', 'verbose_name_plural': 'Student Groups'},
        ),
        migrations.AlterField(
            model_name='student_group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_manager.Teacher'),
        ),
    ]
